//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFrontApplication.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movie()
        {
            this.MovieDirectors = new HashSet<MovieDirector>();
        }
    
        public int MovieID { get; set; }
        public string MovieTitle { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> UnitsSold { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public int RatingID { get; set; }
        public int GenreID { get; set; }
        public int MovieStatusID { get; set; }
        public string MovieImage { get; set; }
        public string Description { get; set; }
    
        public virtual Genre Genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieDirector> MovieDirectors { get; set; }
        public virtual MovieStatu MovieStatu { get; set; }
        public virtual Rating Rating { get; set; }
    }
}
